import Head from 'next/head'
import Header from '../components/header/Header'
import Nav from '../components/nav/Nav'
import Results from '../components/results/Results'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Nav/>
      <Results/>
    </div>
  )
}

export async function getServerSideProps(context){
  
}
